docker_builder:
  only_if: $CIRRUS_TAG != ''
  env:
    DOCKER_USERNAME: ENCRYPTED[d1526f9e9ba2df9fb708e4597998ca5774607eab506fcbd86d78b48d0cb9d7cc8f582b2a6ad3045bf757ace6d41b13d0]
    DOCKER_PASSWORD: ENCRYPTED[460d7bf3f284666cf66ba6b13b400b1e631abad36d633c774236716eed05c38046816589de3f12e961cea8eeb9f0c836]
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build_script: docker buildx build --platform linux/amd64,linux/arm64 --push --tag tecncr/proxitok-url-redirect-bot:$CIRRUS_TAG .
